### ISSUE TITLE
Request: List of environment variables for documentation purposes  

### ISSUE THREAD

**Issue by BKeyport** [MagicMirrorOrg/MagicMirror-Documentation#211]
The recent issue with misquoting how to use an environment variable makes me curious - what variables are available, and how are they used? I'd like to develop out documentation on how to use them, etc. I've been thinking of working on the documentation somewhat, and this seems like a good place to start.

**Comment by BKeyport** [comment]
Take a look at my style here and let me know what you think: 
https://github.com/BKeyport/MagicMirror-Documentation/blob/master/configuration/introduction.md

**Comment by khassel** [comment]
LGTM!

**Comment by BKeyport** [comment]
Closing as complete as every task done.
