### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by bugsounet** [MagicMirrorOrg/MagicMirror-Documentation#222]
No, no I don't forget !

I have to write 2 news Docs for v2.26

 * calendar: `updateOnFetch` feature
 * updatenotification: `updates` , `updateTimeout`, `updateAutorestart`

I will write it as soon as possible, sorry i'm busy actually

**Comment by bugsounet** [comment]
After a lot of month... It's done !

sorry for the delay

**Comment by rejas** [comment]
No need to be sorry, we all have lifes besides mm2 :-)
