### ISSUE TITLE
cleanup README.md (?)

### ISSUE THREAD

**Issue by khassel** [MagicMirrorOrg/MagicMirror-Documentation#249]
In the README.md of this repo these lines exists at the top:

```bash
---
title: Introduction
---
```

Do we need them?

This looks ugly on github:

![grafik](https://github.com/MagicMirrorOrg/MagicMirror-Documentation/assets/25914086/d9f8441d-a570-4fb1-bcab-2dde9c578f78)

**Comment by rejas** [comment]
It does look ugly, but its needed for the menu in the final page. Otherwise it would just say "/" there...
